# Generated by Django 5.0 on 2024-02-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_chatroom_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
